In [2]:
import pandas as pd

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/polina/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/polina/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## read_csv
* filter the rows with index 2 and 3 using the argument skiprows, we know that these observations were fake
* filter the last 2 rows from the footer using the argument skipfooter, we know that these observations were fake too
* assign the following names to the column: datetime, user
* use datetime as the index column
* rename datetime to date_time

In [4]:
df = pd.read_csv("../data/feed-views.log", sep="\t", skiprows=[2,3], skipfooter=2, names=["datetime", "user"], index_col="datetime")
df.index.name = "date_time"
df.head(5)

/var/folders/jb/zkfyxcwx1_z7_qyw8llwwzxw0000gn/T/ipykernel_13039/3422302064.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("../data/feed-views.log", sep="\t", skiprows=[2,3], skipfooter=2, names=["datetime", "user"], index_col="datetime")

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [39]:
df.tail(5)

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

## to_csv
* use ’;’ as the delimiter
* save it to a file with the name feed-views-semicolon.log

In [41]:
df.to_csv("../data/feed-views-semicolon.log", sep=";")