In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
train_part = pd.read_json('data/train.json')
test_part = pd.read_json('data/test.json')

In [4]:
train_part.shape

(49352, 15)

In [5]:
train_qun_99 = train_part['price'].quantile(0.99)
train_qun_01 =  train_part['price'].quantile(0.01)
train_part = train_part[(train_part['price'] < train_qun_99) & (train_part['price'] > train_qun_01)]

test_qun_99 = test_part['price'].quantile(0.99)
test_qun_01 =  test_part['price'].quantile(0.01)
test_part = test_part[(test_part['price'] < test_qun_99) & (test_part['price'] > test_qun_01)]

In [6]:
train_part['interest_level'] = train_part['interest_level'].astype('category').cat.rename_categories(new_categories={'high': 2, 'medium': 1, 'low': 0})

In [221]:
train_part

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address,interest_level
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[Dining Room, Pre-War, Laundry in Building, Di...",40.7108,7170325,-73.9539,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/7170325_3bb5ac84...,2400,145 Borinquen Place,1
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7513,7092344,-73.9722,955db33477af4f40004820b4aed804a0,[https://photos.renthop.com/2/7092344_7663c19a...,3800,230 East 44th,0
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, Laundry in Building, Laund...",40.7575,7158677,-73.9625,c8b10a317b766204f08e613cef4ce7a0,[https://photos.renthop.com/2/7158677_c897a134...,3495,405 East 56th Street,1
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,[https://photos.renthop.com/2/7211212_1ed4542e...,3000,792 Metropolitan Avenue,1
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in...",40.7439,7225292,-73.9743,2c3b41f588fbb5234d8a1e885a436cfa,[https://photos.renthop.com/2/7225292_901f1984...,2795,340 East 34th Street,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124000,1.0,3,92bbbf38baadfde0576fc496bd41749c,2016-04-05 03:58:33,There is 700 square feet of recently renovated...,W 171 Street,"[Elevator, Dishwasher, Hardwood Floors]",40.8433,6824800,-73.9396,a61e21da3ba18c7a3d54cfdcc247e1f8,[https://photos.renthop.com/2/6824800_0682be16...,2800,620 W 171 Street,0
124002,1.0,2,5565db9b7cba3603834c4aa6f2950960,2016-04-02 02:25:31,"2 bedroom apartment with updated kitchen, rece...",Broadway,"[Common Outdoor Space, Cats Allowed, Dogs Allo...",40.8198,6813268,-73.9578,8f90e5e10e8a2d7cf997f016d89230eb,[https://photos.renthop.com/2/6813268_1e6fcc32...,2395,3333 Broadway,1
124004,1.0,1,67997a128056ee1ed7d046bbb856e3c7,2016-04-26 05:42:03,No Brokers Fee * Never Lived 1 Bedroom 1 Bathr...,210 Brighton 15th St,"[Dining Room, Elevator, Pre-War, Laundry in Bu...",40.5765,6927093,-73.9554,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/6927093_93a52104...,1850,210 Brighton 15th St,1
124008,1.0,2,3c0574a740154806c18bdf1fddd3d966,2016-04-19 02:47:33,Wonderful Bright Chelsea 2 Bedroom apartment o...,West 21st Street,"[Pre-War, Laundry in Unit, Dishwasher, No Fee,...",40.7448,6892816,-74.0017,c3cd45f4381ac371507090e9ffabea80,[https://photos.renthop.com/2/6892816_1a8d087a...,4195,350 West 21st Street,1
124009,1.0,3,d89f514c3ed0abaae52cba7017ac0701,2016-04-20 05:34:00,***PRIME MIDTOWN EAST OFF PARK AVE***TRUE 3 BE...,E 54th St,"[Dining Room, Elevator, Laundry in Building, D...",40.7594,6901023,-73.9712,e90f2ded843cdb2efd65ef47d9fc8029,[https://photos.renthop.com/2/6901023_02052d90...,4280,123 E 54th St,2

In [7]:
result_array = []
for index, row in train_part.iterrows():
    for word in row['features']:
        word = word.replace(' ', '').replace('[', '').replace(']', '').replace("'", "").replace('"', '') 
        result_array.append(word)

nunique_rows = pd.Series(result_array).nunique()
nunique_rows

1529

In [223]:
result_array = []
for index, row in test_part.iterrows():
    for word in row['features']:
        word = word.replace(' ', '').replace('[', '').replace(']', '').replace("'", "").replace('"', '') 
        result_array.append(word)

nunique_rows = pd.Series(result_array).nunique()
nunique_rows

2044

In [224]:
from collections import Counter

most_common_features = Counter(result_array).most_common(20)
most_common_features

[('Elevator', 38215),
 ('CatsAllowed', 35017),
 ('HardwoodFloors', 34989),
 ('DogsAllowed', 32576),
 ('Doorman', 30793),
 ('Dishwasher', 30133),
 ('NoFee', 26918),
 ('LaundryinBuilding', 24187),
 ('FitnessCenter', 19762),
 ('Pre-War', 13707),
 ('LaundryinUnit', 12690),
 ('RoofDeck', 9734),
 ('OutdoorSpace', 7923),
 ('DiningRoom', 7303),
 ('HighSpeedInternet', 6189),
 ('Balcony', 4508),
 ('SwimmingPool', 4266),
 ('LaundryInBuilding', 3870),
 ('NewConstruction', 3717),
 ('Terrace', 3201)]

In [ ]:
top_features = []
for tuple in most_common_features:
    feature, count = tuple
    top_features.append(feature)

for feature in top_features:
    train_part[feature] = 0.0
    for i in range(train_part.shape[0]):
        if isinstance(train_part['features'].iloc[i], list) and feature in train_part['features'].iloc[i]:
            train_part[feature].iloc[i] = 1.0 
        else:
            train_part[feature].iloc[i] = 0.0

In [ ]:
for feature in top_features:
    mask = test_part['features'].apply(lambda x: feature in x if isinstance(x, list) else False)
    test_part[feature] = mask.astype(float)

In [227]:
train_part.fillna({'bathrooms': train_part['bathrooms'].mode()[0]}, inplace=True)
train_part.fillna({'bedrooms': train_part['bedrooms'].mode()[0]}, inplace=True)

In [228]:
X_train = train_part[['bathrooms', 'bedrooms'] + top_features].values
y_train = train_part['price'].values
X_test = test_part[['bathrooms', 'bedrooms'] + top_features].values
y_test = test_part['price'].values

data = pd.DataFrame()

In [229]:
np.random.seed(21)
class Lin_Reg_GD:
    def __init__(self, num_objects, num_features, features, y):
        self.num_objects = num_objects
        self.num_features = num_features + 1
        self.features = np.column_stack([np.ones(len(features)), features])
        self.y = y
        np.random.seed(21)
        self.W = np.random.randn(self.num_features)
       
    def MSE(self, y, predictions):
        return (np.mean((y - predictions) ** 2))
    
    def R2(self, y, predictions):
        return 1 - np.sum((y - predictions) ** 2)/np.sum((y - np.mean(y)) ** 2)

    def MAE(self, y, predictions):
        return (np.mean(np.abs(y - predictions)))

    def derivative_MSE(self, predictions):
        der_MSE = -2/(self.num_objects) * self.features.T @ (self.y - predictions)
        return der_MSE
        
    def update_params(self, learning_rate):
        predictions = self.predictions()
        self.W -= learning_rate * self.derivative_MSE(predictions)
        return self.W
    
    def predictions(self):
        predictions = self.features @ self.W 
        return predictions
    
    def predict(self, X_new):
        X_new_with_bias = np.column_stack([np.ones(len(X_new)), X_new])
        return X_new_with_bias @ self.W

class SGD(Lin_Reg_GD):
    def __init__(self, num_objects, num_features, features, y):
            super().__init__(num_objects, num_features, features, y) 

    def Lasso(self, mse, alpha):
        lasso =  mse + alpha * np.abs(self.W) 
        return lasso
    
    def Ridge(self, mse, alpha):
        ridge = mse + alpha * (self.W ** 2)
        return ridge
    
    def ElasticNet(self, mse, alpha, proportion):
        l1_n_l2 = mse + alpha * (proportion * (self.W)**2 + (1 - proportion) * np.abs(self.W))
        return l1_n_l2
            
    def update_random_param(self, learning_rate,  regularization='SGD', alpha=0.1, proportion=0.5):
        ind = np.random.randint(0, self.num_objects)
        x_ind = self.features[ind]
        y_ind = self.y[ind]
        prediction = x_ind @ self.W
        der_MSE = -2 * x_ind * (y_ind - prediction)

        if regularization == 'Ridge':
            loss = self.Ridge(der_MSE, alpha)
        elif regularization == 'Lasso':
            loss = self.Lasso(der_MSE, alpha)
        elif regularization == 'Elastic':
            loss = self.ElasticNet(der_MSE, alpha, proportion)
        else:
            loss = der_MSE
        
        self.W -= learning_rate * loss

In [230]:
def studing_GD(iterations):
    LinReg = Lin_Reg_GD(X_train.shape[0], X_train.shape[1], X_train, y_train)

    for i in range(iterations): 
        LinReg.update_params(learning_rate=0.1)
    
    predictions = LinReg.predict(X_test)
    print(f'RMSE: {LinReg.MSE(y_test, predictions) ** 0.5}')
    print(f'R2: {LinReg.R2(y_test, predictions)}')
    print(f'MAE: {LinReg.MAE(y_test, predictions)}')

studing_GD(iterations=500)

RMSE: 1253.8481405479615
R2: 0.3647995384226451
MAE: 736.6264587762117

In [231]:
np.random.seed(21)
data = pd.DataFrame()

def studing_SGD(iterations, regularization='SGD', alpha=1, proportion=0.5, learning_rate=0.01, X_train=X_train, y_train=y_train, X_test=X_test , y_test=y_test):
    np.random.seed(21)
    LR_SGD = SGD(X_train.shape[0], X_train.shape[1], X_train, y_train)

    for i in range(iterations): 
        LR_SGD.update_random_param(learning_rate=learning_rate, regularization=regularization, alpha=alpha, proportion=proportion)
    
    predictions = LR_SGD.predict(X_test)

    global data
    new_model = {'Model': f'self-created_{regularization}', 
                  'RMSE': LR_SGD.MSE(y_test, predictions) ** 0.5, 
                  'R2': LR_SGD.R2(y_test, predictions), 
                  'MAE': LR_SGD.MAE(y_test, predictions)}
    data = pd.concat([data, pd.DataFrame([new_model])], ignore_index=True)

    print(f'RMSE: {LR_SGD.MSE(y_test, predictions) ** 0.5}')
    print(f'R2: {LR_SGD.R2(y_test, predictions)}')
    print(f'MAE: {LR_SGD.MAE(y_test, predictions)}')

studing_SGD(iterations=1000, learning_rate=0.001)

RMSE: 1191.5505675606369
R2: 0.42635147628816217
MAE: 765.4803919392533

In [232]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error 

def sklearnResults(X_train=X_train, X_test=X_test):
    model = LinearRegression()
    model.fit(X_train, y_train)

    global data
    y_pred = model.predict(X_test)
    new_model = {'Model': f'sklearn_LR', 
                    'RMSE': mean_squared_error(y_test, y_pred)** 0.5, 
                    'R2': r2_score(y_test, y_pred), 
                    'MAE': mean_absolute_error(y_test, y_pred)}
    data = pd.concat([data, pd.DataFrame([new_model])], ignore_index=True)
    print(new_model)

sklearnResults()

{'Model': 'sklearn_LR', 'RMSE': 1253.8753274740006, 'R2': 0.36477199228745993, 'MAE': 736.6317474676483}

In [233]:
studing_SGD(iterations=10000, regularization='Lasso', alpha=0.5, learning_rate=0.001)

RMSE: 1180.4037556925412
R2: 0.4370340996677544
MAE: 750.2240024564059

In [234]:
studing_SGD(iterations=10000, regularization='Ridge', alpha=0.001, learning_rate=0.001)

RMSE: 1180.7429223444615
R2: 0.4367105380219546
MAE: 776.6338633420088

In [235]:
studing_SGD(iterations=10000, regularization='Elastic', alpha=0.001, learning_rate=0.001)

RMSE: 1168.7434061510392
R2: 0.4481014260538728
MAE: 760.9132774636626

In [236]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

def regularization(model, X_train=X_train, X_test=X_test, **kwargs):
    reg_model = model(**kwargs)
    reg_model.fit(X_train, y_train)

    y_pred = reg_model.predict(X_test)

    global data
    model_name = str(model).replace('>', '').replace("'", "").split('.')[-1]
    new_model = {'Model': f'sklearn_{model_name}', 
                  'RMSE': mean_squared_error(y_test, y_pred)** 0.5, 
                  'R2': r2_score(y_test, y_pred), 
                  'MAE': mean_absolute_error(y_test, y_pred)}
    data = pd.concat([data, pd.DataFrame([new_model])], ignore_index=True)
    print(new_model)

In [237]:
regularization(model=Ridge, alpha=0.001)

{'Model': 'sklearn_Ridge', 'RMSE': 1253.8752801443543, 'R2': 0.3647720402429715, 'MAE': 736.6317459619419}

In [238]:
regularization(model=Lasso, alpha=0.001)

{'Model': 'sklearn_Lasso', 'RMSE': 1253.8744433182183, 'R2': 0.36477288813460806, 'MAE': 736.6316016446377}

In [239]:
regularization(model=ElasticNet, alpha=0.001)

{'Model': 'sklearn_ElasticNet', 'RMSE': 1252.7377915693899, 'R2': 0.3659240476406489, 'MAE': 736.5963908741988}

In [240]:
data

                  Model         RMSE        R2         MAE
0      self-created_SGD  1191.550568  0.426351  765.480392
1            sklearn_LR  1253.875327  0.364772  736.631747
2    self-created_Lasso  1180.403756  0.437034  750.224002
3    self-created_Ridge  1180.742922  0.436711  776.633863
4  self-created_Elastic  1168.743406  0.448101  760.913277
5         sklearn_Ridge  1253.875280  0.364772  736.631746
6         sklearn_Lasso  1253.874443  0.364773  736.631602
7    sklearn_ElasticNet  1252.737792  0.365924  736.596391

In [ ]:
def Scaler(type, X):
    if type == 'Standard':
        X_scaled = (X - np.mean(X, axis=0)) / (np.std(X, axis=0) +  1e-8)
        return X_scaled
    elif type == 'MinMax':
        X_scaled = (X - np.min(X, axis=0)) / (np.max(X, axis=0) - np.min(X, axis=0) +  1e-8)
        return X_scaled

In [242]:
X_train_standard = Scaler(type='Standard', X=X_train)
X_test_standard = Scaler(type='Standard', X=X_test)
studing_SGD(iterations=1000, learning_rate=0.001, X_train=X_train_standard, X_test=X_test_standard)

RMSE: 1288.355788492407
R2: 0.3293552167958764
MAE: 786.8420773540663

In [243]:
X_train_minmax= Scaler(type='MinMax', X=X_train)
X_test_minmax = Scaler(type='MinMax', X=X_test)
studing_SGD(iterations=1000, learning_rate=0.001, X_train=X_train_minmax, X_test=X_test_minmax)

RMSE: 1525.1841005685774
R2: 0.06013503015916921
MAE: 1041.5718472340925

In [244]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
MinMax = MinMaxScaler()
X_train_minmax = MinMax.fit_transform(X_train)
X_test_minmax = MinMax.transform(X_test)
sklearnResults(X_train_minmax, X_test_minmax)

{'Model': 'sklearn_LR', 'RMSE': 1253.8753274740986, 'R2': 0.36477199228736057, 'MAE': 736.631747467647}

In [245]:
standardScaler = StandardScaler()
X_train_standard = standardScaler.fit_transform(X_train)
X_test_standard = standardScaler.transform(X_test)
sklearnResults(X_train_standard, X_test_standard)

{'Model': 'sklearn_LR', 'RMSE': 1253.8753274741123, 'R2': 0.3647719922873469, 'MAE': 736.6317474676478}

#### Overfit model

In [246]:
X_train = train_part[['bathrooms', 'bedrooms']]
y_train = train_part['price']

X_test = test_part[['bathrooms', 'bedrooms']]
y_test = test_part['price']

In [247]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=10)
X_poly_train = poly.fit_transform(X_train)
X_poly_test = poly.transform(X_test)

In [248]:
standardScaler = StandardScaler()
X_poly_train = standardScaler.fit_transform(X_poly_train)
X_poly_test = standardScaler.transform(X_poly_test)

In [249]:
studing_SGD(iterations=10000, alpha=0.5, learning_rate=0.01, X_train=X_poly_train, y_train=y_train.values, X_test=X_poly_test, y_test=y_test.values)

RMSE: 1.0599381394836871e+43
R2: -4.539227647222978e+79
MAE: 3.9195575538133297e+40

In [250]:
studing_SGD(iterations=10000, regularization='Ridge', learning_rate=0.00000001, X_train=X_poly_train, y_train=y_train.values, X_test=X_poly_test, y_test=y_test.values)

RMSE: 235035192.47022057
R2: -22319615823.694756
MAE: 872663.7038041633

In [251]:
studing_SGD(iterations=10000, regularization='Lasso', alpha=0.5, learning_rate=0.0001, X_train=X_poly_train, y_train=y_train.values, X_test=X_poly_test, y_test=y_test.values)

RMSE: 695105428084.2509
R2: -1.9521909018031174e+17
MAE: 2570414551.638603

In [252]:
studing_SGD(iterations=10000, regularization='ElasticNet', alpha=0.001, learning_rate=0.0001, X_train=X_poly_train, y_train=y_train.values, X_test=X_poly_test, y_test=y_test.values)

RMSE: 446825964061.6781
R2: -8.066733820212144e+16
MAE: 1652307729.4521577

In [253]:
studing_SGD(iterations=10000, regularization='Lasso', alpha=0.5, learning_rate=0.0001, X_train=X_poly_train, y_train=y_train.values, X_test=X_poly_test, y_test=y_test.values)

RMSE: 695105428084.2509
R2: -1.9521909018031174e+17
MAE: 2570414551.638603

In [254]:
sklearnResults(X_train=X_poly_train, X_test=X_poly_test)

{'Model': 'sklearn_LR', 'RMSE': 1.9575785790446634e+17, 'R2': -1.5483150408163033e+28, 'MAE': 723888090803671.8}

In [255]:
regularization(model=Ridge, X_train=X_poly_train, X_test=X_poly_test, alpha=0.5)

{'Model': 'sklearn_Ridge', 'RMSE': 28783425351318.457, 'R2': -3.34738661891075e+20, 'MAE': 106437518094.03049}

In [256]:
regularization(model=Lasso, X_train=X_poly_train, X_test=X_poly_test, alpha=0.5)

{'Model': 'sklearn_Lasso', 'RMSE': 1083647034667.2479, 'R2': -4.7445673768467405e+17, 'MAE': 4007193090.46753}

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.883e+09, tolerance: 1.215e+07
  model = cd_fast.enet_coordinate_descent(

In [257]:
regularization(model=ElasticNet, X_train=X_poly_train, X_test=X_poly_test, alpha=0.5)

{'Model': 'sklearn_ElasticNet', 'RMSE': 420426719709.2587, 'R2': -7.141699016815589e+16, 'MAE': 1554686561.238696}

### Naive model

In [258]:
test_part['mean'] = test_part['price'].mean()
test_part['median'] = train_part['price'].median()

In [259]:
mean_RMSE = np.sqrt(mean_squared_error(test_part['mean'], y_test))
mean_R2 = r2_score(test_part['mean'], y_test)
mean_MAE = mean_absolute_error(test_part['mean'], y_test)

median_RMSE = np.sqrt(mean_squared_error(test_part['median'], y_test))
median_R2 = r2_score(test_part['median'], y_test)
median_MAE = mean_absolute_error(test_part['median'], y_test)

In [260]:
new_rows = pd.DataFrame([{'Model': 'mean', 'RMSE': mean_RMSE, 'R2': mean_R2, 'MAE': mean_MAE},
            {'Model': 'median', 'RMSE': median_RMSE, 'R2': median_R2, 'MAE': median_MAE}])

data = pd.concat([data, new_rows], axis=0, ignore_index=True)

In [261]:
data

                      Model          RMSE            R2           MAE
0          self-created_SGD  1.191551e+03  4.263515e-01  7.654804e+02
1                sklearn_LR  1.253875e+03  3.647720e-01  7.366317e+02
2        self-created_Lasso  1.180404e+03  4.370341e-01  7.502240e+02
3        self-created_Ridge  1.180743e+03  4.367105e-01  7.766339e+02
4      self-created_Elastic  1.168743e+03  4.481014e-01  7.609133e+02
5             sklearn_Ridge  1.253875e+03  3.647720e-01  7.366317e+02
6             sklearn_Lasso  1.253874e+03  3.647729e-01  7.366316e+02
7        sklearn_ElasticNet  1.252738e+03  3.659240e-01  7.365964e+02
8          self-created_SGD  1.288356e+03  3.293552e-01  7.868421e+02
9          self-created_SGD  1.525184e+03  6.013503e-02  1.041572e+03
10               sklearn_LR  1.253875e+03  3.647720e-01  7.366317e+02
11               sklearn_LR  1.253875e+03  3.647720e-01  7.366317e+02
12         self-created_SGD  1.059938e+43 -4.539228e+79  3.919558e+40
13       self-created_Ridge  2.350352e+08 -2.231962e+10  8.726637e+05
14       self-created_Lasso  6.951054e+11 -1.952191e+17  2.570415e+09
15  self-created_ElasticNet  4.468260e+11 -8.066734e+16  1.652308e+09
16       self-created_Lasso  6.951054e+11 -1.952191e+17  2.570415e+09
17               sklearn_LR  1.957579e+17 -1.548315e+28  7.238881e+14
18            sklearn_Ridge  2.878343e+13 -3.347387e+20  1.064375e+11
19            sklearn_Lasso  1.083647e+12 -4.744567e+17  4.007193e+09
20       sklearn_ElasticNet  4.204267e+11 -7.141699e+16  1.554687e+09
21                     mean  1.573220e+03 -2.992118e+30  1.128895e+03
22                   median  1.617916e+03  0.000000e+00  1.078673e+03