In [2]:
import pandas as pd

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/polina/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/polina/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Read the CSV file and make ID the index column

In [72]:
df = pd.read_csv("../data/auto.csv", index_col="ID")

df.head(5)

       CarNumber  Make_n_model  Refund   Fines  History
ID
0   Y163O8161RUS    Ford Focus     2.0  3200.0      NaN
1    E432XX77RUS  Toyota Camry     1.0  6500.0      NaN
2    7184TT36RUS    Ford Focus     1.0  2100.0      NaN
3   X582HE161RUS    Ford Focus     2.0  2000.0      NaN
4   E34877152RUS    Ford Focus     2.0  6100.0      NaN

## Count the number of observations using the method count()

In [73]:
df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

## Drop the duplicates, taking into account only the following columns: CarNumber, Make_n_model, Fines

In [74]:
df = df.drop_duplicates(subset=["CarNumber", "Make_n_model", "Fines"], keep="last")

df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

## Work with missing values
* check how many values are missing from each column
* drop all the columns with over 500 missing values using the argument thresh, check how many missing values are in each column
* replace all the missing values in the Refund column with the previous value in that column for that cell, use the argument method, check how many values are missing from each column
* replace all the missing values in the Fines column with the mean value of this
column (exclude NA/null values when computing the mean value), check how
many values are missing from each column

In [75]:
df.isnull().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [76]:
thresh = 500
df = df.drop(columns=df.columns[df.isna().sum() > thresh])

df.isnull().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [77]:
df["Refund"] = df["Refund"].fillna(method="ffill")

df.isnull().sum()

/var/folders/jb/zkfyxcwx1_z7_qyw8llwwzxw0000gn/T/ipykernel_687/3008626598.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Refund"] = df["Refund"].fillna(method="ffill")

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [78]:
df["Fines"] = df["Fines"].fillna(df["Fines"].mean())

df.isnull().sum()

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

In [1]:
df

NameError: name 'df' is not defined

## Split and parse the make and model
* use the method apply both for splitting and for extracting the values to the new columns Make and Model
* drop the column Make_n_model
* save the dataframe in the JSON file auto.json

In [79]:
df["Make"] = df["Make_n_model"].apply(lambda x: x.split()[0])
df["Model"] = df["Make_n_model"].apply(lambda x: " ".join(x.split()[1:]) if len(x.split()) > 1 else "NaN")
df = df.drop(columns="Make_n_model")

df

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [87]:
df.to_json("../data/auto.json", orient="records")